version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: capsim-postgres
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: capsim
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: 